- name: 'firm'
  title: 'Our Firm'
  view: 'section.html'
  children:
    - name: 'mission'
      title: 'Our Mission & Commitment'
      view: 'content.html'

    - name: 'partners'
      title: 'Our Partners'
      view: 'content.html'

    - name: 'staff'
      title: 'Our Staff'
      view: 'content.html'

- name: 'services'
  title: 'Our Services'
  view: 'section.html'
  children:
    - name: 'philosophy'
      title: 'Our Service Philosophy'
      view: 'content.html'

    - name: 'approach'
      title: 'Our Approach'
      view: 'content.html'

    - name: 'plan_comparison'
      title: 'Plan Comparison'
      view: 'content.html'
